import { FaYoutube, FaCode } from "react-icons/fa";
import { FaServer, FaDatabase, FaLayerGroup, FaGamepad } from "react-icons/fa6";

// Skill categories with their icons and skills
export const skillCategories = [
  {
    title: "Backend",
    icon: <FaServer className="text-green-500" size={24} />,
    description: "Server-side technologies and databases",
    skills: [
      "Node.js",
      "Express.js",
      "NestJS",
      "Python",
      "Golang",
      "MongoDB",
      "PostgreSQL",
      "Redis",
      "RabbitMQ",
      "RESTful APIs",
      "GraphQL",
      "Microservices",
    ],
  },
  {
    title: "Frontend",
    icon: <FaLayerGroup className="text-green-500" size={24} />,
    description: "Client-side technologies and frameworks",
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "HTML/CSS",
      "Tailwind CSS",
      "Redux",
      "Framer Motion",
      "Responsive Design",
      "Web Accessibility",
    ],
  },
  {
    title: "Blockchain",
    icon: <FaDatabase className="text-green-500" size={24} />,
    description: "Blockchain technologies and smart contracts",
    skills: [
      "Solidity",
      "Ethereum",
      "Binance Smart Chain",
      "Polygon",
      "Hardhat",
      "Foundry",
      "Web3.js",
      "Ethers.js",
      "Smart Contracts",
      "Token Standards",
      "DeFi Protocols",
    ],
  },
  {
    title: "Game Development",
    icon: <FaGamepad className="text-green-500" size={24} />,
    description: "Android game creation with Unity",
    skills: [
      "Unity",
      "C#",
      "Game Design",
      "2D/3D Graphics",
      "Physics",
      "Animation",
      "UI/UX for Games",
      "Mobile Optimization",
      "Game Monetization",
      "Google Play Store",
      "Game Testing",
      "Performance Optimization",
    ],
  },
  {
    title: "Tools",
    icon: <FaCode className="text-green-500" size={24} />,
    description: "Development tools and practices",
    skills: [
      "Git",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "AWS",
      "Linux",
      "VSCode",
      "Jest",
      "Mocha/Chai",
      "Postman",
      "Canva",
      "Notion",
      "Trello",
      "MS Loop",
      "Figma",
    ],
  },
  {
    title: "Media",
    icon: <FaYoutube className="text-green-500" size={24} />,
    description: "Content creation and tutorials",
    skills: [
      "YouTube Tutorials",
      "Technical Writing",
      "Podcasts",
      "Public Speaking",
      "Documentation",
      "Community Building",
    ],
  },
];
